Release notes for PlacesMonitor 2.2.2 and MobileService 1.1.4
Adobe-Marketing-Cloud/aep-sdks-documentation pull request #526
Opened 2021-05-13 22:14 UTC by PravinPK

2021-05-13 23:19 UTC, rymorale approved these changes
👍 looks good

2021-05-14 01:43 UTC, ahmyr requested changes

2021-05-14 01:43 UTC, ahmyr commented on release-notes/README.md
> +* Fixed a bug that caused a crash, when multiple threads were accessing InAppMessages instance.
Comma is not needed here.

2021-05-14 01:43 UTC, ahmyr commented on release-notes/README.md
> +* Fixed a crash, that was caused when application did not find the required activity for requesting location permission.
Comma is not needed here.

2021-05-14 18:54 UTC, merged