Adobe journey optimizer - push messaging guide doc
Adobe-Marketing-Cloud/aep-sdks-documentation pull request #532
Opened 2021-05-24 05:37 UTC by anshikagarwal-git

2021-05-24 06:13 UTC, anshikagarwal-git commented
@calebk1 - This documentation is being added for a holistic picture of Push Messaging flow using Adobe Journey optimizer. Please review whenever you find time. Thanks!
Also tagging @chetanprasad0 and @archanaadobe for review.

2021-05-26 00:54 UTC, calebk1 requested changes
Leaving some feedback.

My biggest comments mostly are about the large gaps between sections (it really only needs to be one line) as well as title casing the headers, when they should be sentence cased, as per the Adobe style guidelines.

2021-05-26 00:54 UTC, calebk1 commented on beta/adobe-journey-optimizer/push-messaging-guide.md
> +[Adobe Launch or Data Collection](https://experienceleague.adobe.com/docs/launch/using/home.html) is the next generation of mobile SDK management capabilities which enables data flow from mobile SDK
"... enables data flow from Mobile SDK to Experience Platform."

2021-05-26 00:54 UTC, calebk1 commented on beta/adobe-journey-optimizer/push-messaging-guide.md
> +[Adobe Launch or Data Collection](https://experienceleague.adobe.com/docs/launch/using/home.html) is the next generation of mobile SDK management capabilities which enables data flow from mobile SDK
"... to register extensions, create rules, and create data elements to send data from your mobile app to Adobe Experience Cloud solutions."

2021-05-26 00:54 UTC, calebk1 commented on beta/adobe-journey-optimizer/push-messaging-guide.md
> +[Adobe Launch or Data Collection](https://experienceleague.adobe.com/docs/launch/using/home.html) is the next generation of mobile SDK management capabilities which enables data flow from mobile SDK
"For the push notifications data flow, the primary configurations required in Launch are:"

2021-05-26 00:54 UTC, calebk1 commented on beta/adobe-journey-optimizer/push-messaging-guide.md
> +- Creating a datastream to configure the profile and experience event datasets against which the data flows into experience platform.
"... the Profile and Experience Event datasets... into Experience Platform."

2021-05-26 00:54 UTC, calebk1 commented on beta/adobe-journey-optimizer/push-messaging-guide.md
> +You will find detailed steps for these configurations [here](https://aep-sdks.gitbook.io/docs/beta/adobe-journey-optimizer).
"You can find detailed steps..."

2021-05-26 00:54 UTC, calebk1 commented on beta/adobe-journey-optimizer/push-messaging-guide.md
> +Static data that identifies the user of the mobile app such as a push token, is stored against the user's profile as record data while the interactions the user does with push notifications are track
"... the mobile app, such as a push token, is stored against the user's profile as record data, while the user's interactions with push notifications are tracked as time-series event data."

2021-05-26 00:54 UTC, calebk1 commented on beta/adobe-journey-optimizer/push-messaging-guide.md
> +Once your mobile app integrations with above mentioned components are in place and your customer profiles are available as Real-time customer profiles, you can take advantage of powerful audience seg
"Once your mobile app integrates with the previously mentioned components and your customer profiles are available as Real-Time Customer Profiles, you can..."

2021-05-26 00:54 UTC, calebk1 commented on beta/adobe-journey-optimizer/push-messaging-guide.md
> +### Push Data Flow Steps
Same comment about title vs. sentence casing.

2021-05-26 00:54 UTC, calebk1 commented on beta/adobe-journey-optimizer/push-messaging-guide.md
> +1. The customer develops a mobile app on Android or iOS that they would release to their users. In order to use the push capability provided by push providers i.e APNS by Apple and FCM by Google, the
"In order to use the push capability provided by the providers (APNS for Apple and FCM for Google), the mobile app..."

2021-05-26 00:54 UTC, calebk1 commented on beta/adobe-journey-optimizer/push-messaging-guide.md
> +Refer to the data flow diagram to identify what each of these bullets represent :
To identify what each of the numbers represent, please refer to the data flow diagram:

2021-05-26 00:54 UTC, calebk1 commented on beta/adobe-journey-optimizer/push-messaging-guide.md
> +2. The push providers generate and send a push token to the mobile app. A Push Token is an identifier that senders use to target specific devices with a push notification.
Does push token need to be capitalized?

2021-05-26 00:54 UTC, calebk1 commented on beta/adobe-journey-optimizer/push-messaging-guide.md
> +3. The mobile app is integrated with Adobe Mobile SDK which exposes various extensions and APIs. The Messaging extension exposes an API to register the push token into Adobe Experience Platform again
"... integrated with Mobile SDK, which exposes...".

Also, does messaging need to be capitalized?

2021-05-26 00:54 UTC, calebk1 commented on beta/adobe-journey-optimizer/push-messaging-guide.md
> +7. The personalized push message is sent for further processing to the Push delivery service.
Does push need to be capitalized here?

2021-05-26 00:54 UTC, calebk1 commented on beta/adobe-journey-optimizer/push-messaging-guide.md
> +10. The push providers send a feedback suggesting whether the message was successfully delivered to the provider or not. In case not, the relevant error message is part of the feedback. This feedback
"If the message was not successfully delivered, the relevant error message is sent as part of the feedback."

2021-05-26 00:54 UTC, calebk1 commented on beta/adobe-journey-optimizer/push-messaging-guide.md
> +## Understanding Push User Flow
Same comment about sentence vs. title case.

2021-06-21 20:39 UTC, anshikagarwal-git commented
We are not going ahead with this PR merge. The document has been published as part of AJO docs here :
https://experienceleague.adobe.com/docs/journey-optimizer/using/get-started/configuration/push-config/push-gs.html?lang=en

2021-06-21 20:39 UTC, closed without merging