Mobile extension mobile services
Adobe-Marketing-Cloud/aep-sdks-documentation pull request #596
Opened 2021-07-13 18:10 UTC by calebk1

2021-07-22 21:39 UTC, yangyansong-adbe requested changes
LGTM! Just a few comments.

2021-07-22 21:39 UTC, yangyansong-adbe commented on using-mobile-extensions/adobe-analytics-mobile-services/README.md
> +To use location functionality for Mobile Services, see the documentation on the [Places Service](https://experienceleague.adobe.com/docs/places/using/home.html?lang=en), the point of interest managem
The `Location` functionality (https://experienceleague.adobe.com/docs/mobile-services/using/location-ug/location-overview.html?lang=en) is no longer supported by the `Mobile Services` extension. The `Places Service` is an replacement for the users interested in location-based services.

2021-07-22 21:39 UTC, yangyansong-adbe commented on using-mobile-extensions/adobe-analytics-mobile-services/README.md
> +No set up is required. On Android, the SDK automatically handles push tracking to Analytics.
`No setup is required`

2021-07-22 21:39 UTC, yangyansong-adbe commented on using-mobile-extensions/adobe-analytics-mobile-services/README.md
> +```swift
should be `objectivec` here.

2021-07-22 21:39 UTC, yangyansong-adbe commented on using-mobile-extensions/adobe-analytics-mobile-services/README.md
> +If you are using a fullscreen message or a local notification, update the `AndroidManifest.xml` with the following:
If you are using `fullscreen message` functionality or `local notification` functionality, update ...

2021-07-22 21:39 UTC, yangyansong-adbe commented on using-mobile-extensions/adobe-analytics-mobile-services/README.md
> +No set up is required, since Acquisition context is automatically collected and tracked by the SDK.
No setup is required.

2021-08-11 19:06 UTC, calebk1 commented
@emdobrin  - Yup, just haven't had time to work on this recently as I've been busy with other asks. I'll pick this up as soon as I can again.

2021-08-20 02:06 UTC, emdobrin approved these changes

2021-08-20 02:06 UTC, merged