Target v1.2.8 release notes
Adobe-Marketing-Cloud/aep-sdks-documentation pull request #616
Opened 2021-08-23 22:50 UTC by shtomar-adb

Target v1.2.8 release notes

2021-08-23 22:57 UTC, calebk1 approved these changes
LGTM!

2021-08-23 23:08 UTC, swarna04 commented on release-notes/README.md
> +* Added support for sending the click conversion A4T payload to Adobe Analytics for A4T-enabled Target activities when the `clickedLocation` API is called.
Android API is `locationClicked`

2021-08-23 23:09 UTC, swarna04 requested changes

2021-08-23 23:09 UTC, swarna04 commented on using-mobile-extensions/adobe-target/adobe-target-release-notes.md
> +* Added support for sending the click conversion A4T payload to Adobe Analytics for A4T-enabled Target activities when the `clickedLocation` API is called.
Same as above, API is `locationClicked`

2021-08-24 05:04 UTC, swarna04 approved these changes

2021-08-24 18:24 UTC, merged