Update release notes for AEPCore 3.7.1
Adobe-Marketing-Cloud/aep-sdks-documentation pull request #803
Opened 2022-08-11 15:11 UTC by cdhoffmann

2022-08-16 23:57 UTC, praveek approved these changes

2022-08-16 23:58 UTC, praveek requested changes
Can you also update the MobileCore release notes page?

2022-08-16 23:58 UTC, calebk1 approved these changes
LGTM!

2022-08-17 16:03 UTC, cdhoffmann commented
@praveek Done

2022-08-18 17:51 UTC, praveek approved these changes

2022-08-18 18:00 UTC, merged